### ISSUE TITLE
Remove all platform examples in example repo other than Cypress

### ISSUE THREAD

**Issue by dequejenn** [dequelabs/axe-watcher-examples#75]
The only folder that should remain in the axe-watcher-examples repo is the Cypress folder. The others will be added back in once we wrap each of those drivers so don't completely get rid of to where we can't easily bring them back.

**Comment by gayathrit12** [comment]
This is working as expected.

## Screenshot:
![image](https://user-images.githubusercontent.com/102580833/223715608-7312723d-aad5-4b63-90e3-4eabcde2ba75.png)

## Environment:
| **Label**                         | **Value** |
| -------------------------- | ------ |
| **Server URL**                | _https://axe.dequelabs.com/_ |
| **Server version**           | _4.68.0_ |
| **@axe-core/watcher version**      | _1.4.0-next.4ab4bc6e_ |
